import type { Theme } from './types';

export const extraThemes: Theme[] = [
  {
    id: 'solarized',
    name: 'Solarized',
    description: '经典暖色调开发者配色，柔和护眼的阅读体验',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #657b83 !important; background-color: #fdf6e3 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #cb4b16 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #268bd2 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #2aa198 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #657b83 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #657b83 !important;',
      strong: 'font-weight: 700; color: #cb4b16 !important;',
      em: 'font-style: italic; color: #93a1a1 !important;',
      a: 'color: #268bd2 !important; text-decoration: none; border-bottom: 1px solid #268bd2; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #657b83 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #eee8d5 !important; border-left: 4px solid #2aa198; color: #586e75 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #eee8d5 !important; color: #859900 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #eee8d5 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eee8d5 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #eee8d5 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #657b83 !important; border: 1px solid #ddd6c1;',
      td: 'padding: 12px 16px; border: 1px solid #ddd6c1; color: #657b83 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    description: '霓虹闪烁的赛博朋克世界，品红与青的极致碰撞',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: "SF Mono", "Fira Code", Consolas, monospace; font-size: 15px; line-height: 1.7 !important; color: #e0e0ff !important; background-color: #0d0221 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #ff2a6d !important; text-shadow: 0 0 8px rgba(255,42,109,0.5); line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: 0.05em; text-transform: uppercase;',
      h2: 'font-size: 26px; font-weight: 600; color: #05d9e8 !important; text-shadow: 0 0 8px rgba(5,217,232,0.5); line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #d1f7ff !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #ff2a6d !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #e0e0ff !important;',
      strong: 'font-weight: 700; color: #ff2a6d !important; text-shadow: 0 0 6px rgba(255,42,109,0.4);',
      em: 'font-style: italic; color: #05d9e8 !important;',
      a: 'color: #05d9e8 !important; text-decoration: none; border-bottom: 1px solid #05d9e8; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #e0e0ff !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #1a0a3e !important; border-left: 4px solid #ff2a6d; color: #c8c8ff !important; border-radius: 0;',
      code: 'font-family: "SF Mono", "Fira Code", Consolas, monospace; padding: 3px 6px; background-color: #1a0a3e !important; color: #05d9e8 !important; border-radius: 0; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #2a1a4e;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #1a0a3e !important; border-radius: 0; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #2a1a4e;',
      hr: 'margin: 36px auto; border: none; height: 2px; background: linear-gradient(90deg, #ff2a6d, #05d9e8) !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 0;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 14px;',
      th: 'background-color: #1a0a3e !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #ff2a6d !important; border: 1px solid #2a1a4e;',
      td: 'padding: 12px 16px; border: 1px solid #2a1a4e; color: #e0e0ff !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'ink',
    name: '水墨',
    description: '纯粹的黑白水墨风，零色彩干扰的极简阅读',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, "Times New Roman", Times, serif; font-size: 16px; line-height: 1.8 !important; color: #111111 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #000000 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.02em; border-bottom: 2px solid #000; padding-bottom: 10px;',
      h2: 'font-size: 26px; font-weight: 700; color: #000000 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #222222 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 20px 0 !important; line-height: 1.8 !important; color: #111111 !important;',
      strong: 'font-weight: 700; color: #000000 !important;',
      em: 'font-style: italic; color: #555555 !important;',
      a: 'color: #111111 !important; text-decoration: underline; text-underline-offset: 3px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.8 !important; color: #111111 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: transparent !important; border-left: 3px solid #000000; color: #333333 !important; border-radius: 0;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f0f0f0 !important; color: #000000 !important; border-radius: 2px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f5f5f5 !important; border-radius: 2px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #e0e0e0;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #000000 !important; width: 40%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 0;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f5f5f5 !important; padding: 12px 16px; text-align: left; font-weight: 700; color: #000000 !important; border: 1px solid #cccccc;',
      td: 'padding: 12px 16px; border: 1px solid #cccccc; color: #111111 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'lavender',
    name: '薰衣草',
    description: '梦幻紫色调的浪漫氛围，诗意与灵感的温柔表达',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.75 !important; color: #3d3155 !important; background-color: #f5f0ff !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #6b4c9a !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #7c5cad !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #3d3155 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #3d3155 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.75 !important; color: #3d3155 !important;',
      strong: 'font-weight: 700; color: #6b4c9a !important; background-color: rgba(107,76,154,0.08); padding: 0 4px; border-radius: 4px;',
      em: 'font-style: italic; color: #8a6dba !important;',
      a: 'color: #6b4c9a !important; text-decoration: none; border-bottom: 1px solid rgba(107,76,154,0.3); padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.75 !important; color: #3d3155 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #ece4ff !important; border-left: 4px solid #9b7fd4; color: #5a4570 !important; border-radius: 8px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #ece4ff !important; color: #6b4c9a !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #ece4ff !important; border-radius: 12px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #ddd0f0 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #ece4ff !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #3d3155 !important; border: 1px solid #ddd0f0;',
      td: 'padding: 12px 16px; border: 1px solid #ddd0f0; color: #3d3155 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'forest',
    name: '密林',
    description: '深邃的暗绿色丛林，自然与神秘感的沉浸式叙事',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #c8dcc8 !important; background-color: #1a2e1a !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #7dce82 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #a8d8a8 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #8fbc8f !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #c8dcc8 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #c8dcc8 !important;',
      strong: 'font-weight: 700; color: #7dce82 !important;',
      em: 'font-style: italic; color: #a0c8a0 !important;',
      a: 'color: #7dce82 !important; text-decoration: none; border-bottom: 1px solid #7dce82; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #c8dcc8 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #243824 !important; border-left: 4px solid #4a8b4a; color: #a8c8a8 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #243824 !important; color: #7dce82 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #243824 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #3a5a3a !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #243824 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #7dce82 !important; border: 1px solid #3a5a3a;',
      td: 'padding: 12px 16px; border: 1px solid #3a5a3a; color: #c8dcc8 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'glacier',
    name: '冰川',
    description: '清冽的冰蓝色调，冷静理性的科技分析与报告',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #2c3e50 !important; background-color: #eef4fa !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #1565c0 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #1976d2 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #2c3e50 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #2c3e50 !important;',
      strong: 'font-weight: 700; color: #1565c0 !important;',
      em: 'font-style: italic; color: #5a7a9a !important;',
      a: 'color: #1976d2 !important; text-decoration: none; border-bottom: 1px solid rgba(25,118,210,0.3); padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #2c3e50 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #e1eef6 !important; border-left: 4px solid #42a5f5; color: #3a5068 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #e1eef6 !important; color: #1565c0 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #e1eef6 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #c8dce8 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #e1eef6 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2c3e50 !important; border: 1px solid #c8dce8;',
      td: 'padding: 12px 16px; border: 1px solid #c8dce8; color: #2c3e50 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'coffee',
    name: '咖啡',
    description: '醇厚巧克力棕色调，午后咖啡馆的温暖书卷气',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, "Times New Roman", Times, serif; font-size: 16px; line-height: 1.75 !important; color: #3e2723 !important; background-color: #f5efe6 !important; background-image: radial-gradient(circle at center, #f5efe6 0%, #ebe2d3 100%); word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #4e342e !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #5d4037 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #3e2723 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #3e2723 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.75 !important; color: #3e2723 !important;',
      strong: 'font-weight: 700; color: #4e342e !important;',
      em: 'font-style: italic; color: #795548 !important;',
      a: 'color: #6d4c41 !important; text-decoration: none; border-bottom: 1px solid rgba(109,76,65,0.3); padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.75 !important; color: #3e2723 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #ece2d4 !important; border-left: 4px solid #a1887f; color: #5d4037 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #ece2d4 !important; color: #6d4c41 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #ece2d4 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #d7ccc8 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #ece2d4 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #3e2723 !important; border: 1px solid #d7ccc8;',
      td: 'padding: 12px 16px; border: 1px solid #d7ccc8; color: #3e2723 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'bauhaus',
    name: 'Bauhaus',
    description: '包豪斯三原色风格，红蓝黄碰撞的现代主义先锋',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.65 !important; color: #1a1a1a !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 34px; font-weight: 900; color: #e30613 !important; line-height: 1.2 !important; margin: 38px 0 16px; letter-spacing: -0.02em; text-transform: uppercase;',
      h2: 'font-size: 26px; font-weight: 700; color: #004d9f !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #1a1a1a !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #1a1a1a !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.65 !important; color: #1a1a1a !important;',
      strong: 'font-weight: 900; color: #e30613 !important;',
      em: 'font-style: italic; color: #555 !important;',
      a: 'color: #004d9f !important; text-decoration: none; border-bottom: 2px solid #f5a623; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.65 !important; color: #1a1a1a !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #fff4d6 !important; border-left: 6px solid #f5a623; color: #333 !important; border-radius: 0;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f0f0f0 !important; color: #004d9f !important; border-radius: 0; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f0f0f0 !important; border-radius: 0; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border-left: 6px solid #e30613;',
      hr: 'margin: 36px auto; border: none; height: 3px; background-color: #1a1a1a !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 0;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #004d9f !important; padding: 16px 16px; text-align: left; font-weight: 700; color: #ffffff !important; border: 3px solid #1a1a1a;',
      td: 'padding: 16px 16px; border: 3px solid #1a1a1a; color: #1a1a1a !important; font-weight: 500;',
      tr: 'border: none;',
    }
  },
  {
    id: 'copper',
    name: '赤铜',
    description: '暗夜中的青铜古韵，深沉温暖的金属质感暗色调',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, "Times New Roman", Times, serif; font-size: 16px; line-height: 1.7 !important; color: #d4b896 !important; background-color: #1c1410 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #e8a87c !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #c49070 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #d4b896 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #d4b896 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #d4b896 !important;',
      strong: 'font-weight: 700; color: #e8a87c !important;',
      em: 'font-style: italic; color: #b89878 !important;',
      a: 'color: #e8a87c !important; text-decoration: none; border-bottom: 1px solid #e8a87c; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #d4b896 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #2a1e16 !important; border-left: 4px solid #b8734a; color: #c0a080 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #2a1e16 !important; color: #e8a87c !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #2a1e16 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #3a2a1e !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #2a1e16 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #e8a87c !important; border: 1px solid #3a2a1e;',
      td: 'padding: 12px 16px; border: 1px solid #3a2a1e; color: #d4b896 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'pastel',
    name: '彩虹糖',
    description: '多彩柔和的马卡龙色系，活泼甜美的少年感表达',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.75 !important; color: #4a4a5a !important; background-color: #fefcf8 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #e07a94 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #7ab8d0 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #85b882 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #d4a76a !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.75 !important; color: #4a4a5a !important;',
      strong: 'font-weight: 700; color: #e07a94 !important;',
      em: 'font-style: italic; color: #9b8ec4 !important;',
      a: 'color: #7ab8d0 !important; text-decoration: none; border-bottom: 1px solid rgba(122,184,208,0.4); padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.75 !important; color: #4a4a5a !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #f0ecff !important; border-left: 4px solid #b8a9e0; color: #5a5a6a !important; border-radius: 12px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #fff0f3 !important; color: #e07a94 !important; border-radius: 6px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f0f7ff !important; border-radius: 12px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 2px; background: linear-gradient(90deg, #e07a94, #7ab8d0, #85b882, #d4a76a) !important; width: 100%; border-radius: 2px;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0ecff !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #4a4a5a !important; border: 1px solid #e8e0f0;',
      td: 'padding: 12px 16px; border: 1px solid #e8e0f0; color: #4a4a5a !important;',
      tr: 'border: none;',
    }
  },
];
