import type { Theme } from './types';

export const modernThemes: Theme[] = [
  {
    id: 'notion',
    name: 'Notion',
    description: '极致克制的黑白灰，纯粹信息密度与无干扰写作',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #37352f !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 34px; font-weight: 700; color: #37352f !important; line-height: 1.2 !important; margin: 38px 0 8px; letter-spacing: -0.02em;',
      h2: 'font-size: 26px; font-weight: 600; color: #37352f !important; line-height: 1.3 !important; margin: 32px 0 8px;',
      h3: 'font-size: 21px; font-weight: 600; color: #37352f !important; line-height: 1.35 !important; margin: 28px 0 8px;',
      h4: 'font-size: 18px; font-weight: 600; color: #37352f !important; line-height: 1.4 !important; margin: 24px 0 8px;',
      p: 'margin: 4px 0 !important; line-height: 1.6 !important; color: #37352f !important;',
      strong: 'font-weight: 700; color: #37352f !important;',
      em: 'font-style: italic; color: #37352f !important;',
      a: 'color: #37352f !important; text-decoration: underline; text-underline-offset: 3px; text-decoration-color: rgba(55,53,47,0.4);',
      ul: 'margin: 4px 0; padding-left: 26px;',
      ol: 'margin: 4px 0; padding-left: 26px;',
      li: 'margin: 2px 0; line-height: 1.6 !important; color: #37352f !important;',
      blockquote: 'margin: 8px 0; padding: 4px 16px; background-color: transparent !important; border-left: 3px solid #37352f; color: #37352f !important; border-radius: 0;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 2px 5px; background-color: #f7f6f3 !important; color: #eb5757 !important; border-radius: 3px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 16px 0; padding: 20px; background-color: #f7f6f3 !important; border-radius: 4px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important;',
      hr: 'margin: 24px auto; border: none; height: 1px; background-color: #e9e9e7 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 2px;',
      table: 'width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f7f6f3 !important; padding: 8px 12px; text-align: left; font-weight: 600; color: #37352f !important; border: 1px solid #e9e9e7;',
      td: 'padding: 8px 12px; border: 1px solid #e9e9e7; color: #37352f !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'github',
    name: 'GitHub',
    description: '开发者最熟悉的阅读界面，README 即视感',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.6 !important; color: #1f2328 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 10px; border-bottom: 1px solid #d1d9e0;',
      h2: 'font-size: 24px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px; padding-bottom: 8px; border-bottom: 1px solid #d1d9e0;',
      h3: 'font-size: 20px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;',
      h4: 'font-size: 16px; font-weight: 600; color: #1f2328 !important; line-height: 1.25 !important; margin: 24px 0 16px;',
      p: 'margin: 16px 0 !important; line-height: 1.6 !important; color: #1f2328 !important;',
      strong: 'font-weight: 600; color: #1f2328 !important;',
      em: 'font-style: italic; color: #1f2328 !important;',
      a: 'color: #0969da !important; text-decoration: underline; text-underline-offset: 2px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 4px 0; line-height: 1.6 !important; color: #1f2328 !important;',
      blockquote: 'margin: 16px 0; padding: 8px 16px; background-color: transparent !important; border-left: 4px solid #d0d7de; color: #656d76 !important; border-radius: 0;',
      code: 'font-family: "SF Mono", Consolas, "Liberation Mono", Menlo, monospace; padding: 3px 6px; background-color: rgba(175,184,193,0.2) !important; color: #1f2328 !important; border-radius: 6px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 16px 0; padding: 16px; background-color: #f6f8fa !important; border-radius: 6px; overflow-x: auto; font-size: 13px !important; line-height: 1.45 !important;',
      hr: 'margin: 24px auto; border: none; height: 3px; background-color: #d1d9e0 !important; width: 100%; border-radius: 2px;',
      img: 'max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 6px;',
      table: 'width: 100%; margin: 16px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f6f8fa !important; padding: 8px 16px; text-align: left; font-weight: 600; color: #1f2328 !important; border: 1px solid #d1d9e0;',
      td: 'padding: 8px 16px; border: 1px solid #d1d9e0; color: #1f2328 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'sspai',
    name: '少数派',
    description: '中文数字媒体标杆，经典红色标识与精致排版',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.8 !important; color: #333333 !important; background-color: #ffffff !important; word-wrap: break-word;',
      h1: 'font-size: 28px; font-weight: 700; color: #d71a1b !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.01em;',
      h2: 'font-size: 22px; font-weight: 700; color: #333333 !important; line-height: 1.35 !important; margin: 32px 0 14px; padding-left: 12px; border-left: 4px solid #d71a1b;',
      h3: 'font-size: 18px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 28px 0 12px;',
      h4: 'font-size: 16px; font-weight: 600; color: #333333 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 20px 0 !important; line-height: 1.8 !important; color: #333333 !important;',
      strong: 'font-weight: 700; color: #d71a1b !important;',
      em: 'font-style: italic; color: #666 !important;',
      a: 'color: #d71a1b !important; text-decoration: none; border-bottom: 1px solid rgba(215,26,27,0.3); padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.8 !important; color: #333333 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #fef7f7 !important; border-left: 4px solid #d71a1b; color: #555 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #fff5f5 !important; color: #d71a1b !important; border-radius: 4px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #fafafa !important; border-radius: 8px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important; border: 1px solid #f0f0f0;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #eee !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #fef7f7 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #333 !important; border: 1px solid #f0e0e0;',
      td: 'padding: 12px 16px; border: 1px solid #f0e0e0; color: #333333 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'dracula',
    name: 'Dracula',
    description: '暗紫色赛博吸血鬼美学，粉青撞色的视觉冲击',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #f8f8f2 !important; background-color: #282a36 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #bd93f9 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #ff79c6 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #8be9fd !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #50fa7b !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #f8f8f2 !important;',
      strong: 'font-weight: 700; color: #ffb86c !important;',
      em: 'font-style: italic; color: #8be9fd !important;',
      a: 'color: #8be9fd !important; text-decoration: none; border-bottom: 1px solid #8be9fd; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #f8f8f2 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #44475a !important; border-left: 4px solid #bd93f9; color: #f8f8f2 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #44475a !important; color: #50fa7b !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #44475a !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #6272a4 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #44475a !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #bd93f9 !important; border: 1px solid #6272a4;',
      td: 'padding: 12px 16px; border: 1px solid #6272a4; color: #f8f8f2 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'nord',
    name: 'Nord',
    description: '北欧极地冰霜蓝，冷静克制的极光美学',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #d8dee9 !important; background-color: #2e3440 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #88c0d0 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #81a1c1 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #88c0d0 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #d8dee9 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #d8dee9 !important;',
      strong: 'font-weight: 700; color: #eceff4 !important;',
      em: 'font-style: italic; color: #a3be8c !important;',
      a: 'color: #88c0d0 !important; text-decoration: none; border-bottom: 1px solid #88c0d0; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #d8dee9 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #3b4252 !important; border-left: 4px solid #5e81ac; color: #d8dee9 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #3b4252 !important; color: #a3be8c !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #3b4252 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #4c566a !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #3b4252 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #88c0d0 !important; border: 1px solid #4c566a;',
      td: 'padding: 12px 16px; border: 1px solid #4c566a; color: #d8dee9 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'sakura',
    name: '樱花',
    description: '柔粉色系日式美学，温柔感性的少女心表达',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.75 !important; color: #4a3f4f !important; background-color: #fef7f9 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #c44569 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #c44569 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #4a3f4f !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #4a3f4f !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.75 !important; color: #4a3f4f !important;',
      strong: 'font-weight: 700; color: #c44569 !important; background-color: rgba(196,69,105,0.06); padding: 0 4px; border-radius: 4px;',
      em: 'font-style: italic; color: #9b7fa7 !important;',
      a: 'color: #c44569 !important; text-decoration: none; border-bottom: 1px solid rgba(196,69,105,0.3); padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.75 !important; color: #4a3f4f !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #fceef2 !important; border-left: 4px solid #e8a0b4; color: #6b5570 !important; border-radius: 8px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #fceef2 !important; color: #c44569 !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #fceef2 !important; border-radius: 12px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #f0d4dd !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 12px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #fceef2 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #4a3f4f !important; border: 1px solid #f0d4dd;',
      td: 'padding: 12px 16px; border: 1px solid #f0d4dd; color: #4a3f4f !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'ocean',
    name: '深海',
    description: '午夜深蓝配珊瑚橘，沉浸式的海洋系叙事感',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #c8d6e5 !important; background-color: #0c2233 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #ff6b6b !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #feca57 !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #54a0ff !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #c8d6e5 !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #c8d6e5 !important;',
      strong: 'font-weight: 700; color: #feca57 !important;',
      em: 'font-style: italic; color: #78e0a0 !important;',
      a: 'color: #ff6b6b !important; text-decoration: none; border-bottom: 1px solid #ff6b6b; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #c8d6e5 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #152d42 !important; border-left: 4px solid #54a0ff; color: #c8d6e5 !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #152d42 !important; color: #ff6b6b !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #152d42 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #1e3a52 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #152d42 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #feca57 !important; border: 1px solid #1e3a52;',
      td: 'padding: 12px 16px; border: 1px solid #1e3a52; color: #c8d6e5 !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'mint',
    name: '薄荷',
    description: '清凉薄荷绿底色，适合生活方式与健康类内容',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; font-size: 16px; line-height: 1.7 !important; color: #2d4a3e !important; background-color: #f0faf5 !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #1a7a5a !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #1a7a5a !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #2d4a3e !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #2d4a3e !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #2d4a3e !important;',
      strong: 'font-weight: 700; color: #1a7a5a !important;',
      em: 'font-style: italic; color: #5a8a72 !important;',
      a: 'color: #1a7a5a !important; text-decoration: none; border-bottom: 1px solid rgba(26,122,90,0.3); padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #2d4a3e !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #e0f5ec !important; border-left: 4px solid #1a7a5a; color: #3d5a4e !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #e0f5ec !important; color: #1a7a5a !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #e0f5ec !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #c8e6d8 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 8px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #e0f5ec !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #2d4a3e !important; border: 1px solid #c8e6d8;',
      td: 'padding: 12px 16px; border: 1px solid #c8e6d8; color: #2d4a3e !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'sunset',
    name: '日落',
    description: '暖琥珀色调的黄昏意境，散文游记与情感表达',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: Georgia, "Times New Roman", Times, serif; font-size: 16px; line-height: 1.8 !important; color: #3d2c1e !important; background-color: #fdf6ee !important; word-wrap: break-word;',
      h1: 'font-size: 32px; font-weight: 700; color: #c0582a !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.015em;',
      h2: 'font-size: 26px; font-weight: 600; color: #c0582a !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 21px; font-weight: 600; color: #3d2c1e !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 18px; font-weight: 600; color: #3d2c1e !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 20px 0 !important; line-height: 1.8 !important; color: #3d2c1e !important;',
      strong: 'font-weight: 700; color: #c0582a !important;',
      em: 'font-style: italic; color: #8a6d4b !important;',
      a: 'color: #c0582a !important; text-decoration: none; border-bottom: 1px solid rgba(192,88,42,0.3); padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.8 !important; color: #3d2c1e !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #f8ead6 !important; border-left: 4px solid #e8a65d; color: #5a4232 !important; border-radius: 4px; font-style: italic;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f5e6d0 !important; color: #c0582a !important; border-radius: 4px; font-size: 12px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f5e6d0 !important; border-radius: 8px; overflow-x: auto; font-size: 12px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #e8d4b8 !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f5e6d0 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #3d2c1e !important; border: 1px solid #e8d4b8;',
      td: 'padding: 12px 16px; border: 1px solid #e8d4b8; color: #3d2c1e !important;',
      tr: 'border: none;',
    }
  },
  {
    id: 'monokai',
    name: 'Monokai',
    description: '经典代码编辑器配色，程序员的终极浪漫',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 24px 20px 48px 20px; font-family: "SF Mono", "Fira Code", Consolas, monospace; font-size: 15px; line-height: 1.7 !important; color: #f8f8f2 !important; background-color: #272822 !important; word-wrap: break-word;',
      h1: 'font-size: 30px; font-weight: 700; color: #f92672 !important; line-height: 1.3 !important; margin: 38px 0 16px; letter-spacing: -0.01em;',
      h2: 'font-size: 24px; font-weight: 600; color: #a6e22e !important; line-height: 1.35 !important; margin: 32px 0 16px;',
      h3: 'font-size: 20px; font-weight: 600; color: #e6db74 !important; line-height: 1.4 !important; margin: 28px 0 14px;',
      h4: 'font-size: 17px; font-weight: 600; color: #66d9ef !important; line-height: 1.4 !important; margin: 24px 0 12px;',
      p: 'margin: 18px 0 !important; line-height: 1.7 !important; color: #f8f8f2 !important;',
      strong: 'font-weight: 700; color: #f92672 !important;',
      em: 'font-style: italic; color: #e6db74 !important;',
      a: 'color: #66d9ef !important; text-decoration: none; border-bottom: 1px solid #66d9ef; padding-bottom: 1px;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.7 !important; color: #f8f8f2 !important;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #3e3d32 !important; border-left: 4px solid #f92672; color: #a6a68a !important; border-radius: 4px;',
      code: 'font-family: "SF Mono", "Fira Code", Consolas, monospace; padding: 3px 6px; background-color: #3e3d32 !important; color: #a6e22e !important; border-radius: 4px; font-size: 13px !important; line-height: 1.5 !important;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #3e3d32 !important; border-radius: 8px; overflow-x: auto; font-size: 13px !important; line-height: 1.5 !important;',
      hr: 'margin: 36px auto; border: none; height: 1px; background-color: #49483e !important; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto; border-radius: 4px;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 14px;',
      th: 'background-color: #3e3d32 !important; padding: 12px 16px; text-align: left; font-weight: 600; color: #a6e22e !important; border: 1px solid #49483e;',
      td: 'padding: 12px 16px; border: 1px solid #49483e; color: #f8f8f2 !important;',
      tr: 'border: none;',
    }
  },
];
